after_success:
- if [ "$TRAVIS_JDK_VERSION" == "oraclejdk8" ] && [ "$TRAVIS_BRANCH" == "master" ]
  && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then travis_wait mvn deploy --settings
  core/files/settings.xml -DskipTests=true -B; else echo "Not deploying snapshot artifact
  for $TRAVIS_BRANCH"; fi
before_install:
- if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget --no-check-certificate $(echo -n
  $BASEURL | sed -e 's#VERSION#'$VERSION'#g'); unzip -qq $(echo -n $FILE | sed -e
  's#VERSION#'$VERSION'#'); export M2_HOME=$PWD/$(echo -n $DIR | sed -e 's#VERSION#'$VERSION'#');
  export PATH=$M2_HOME/bin:$PATH; fi
- if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$JVM" == "latest" ]; then sudo apt-get
  update -qq; sudo /bin/echo -e oracle-java9-installer shared/accepted-oracle-license-v1-1
  select true | sudo debconf-set-selections; sudo apt-get -o Dpkg::Options::="--force-confnew"
  install -y oracle-java9-installer oracle-java9-set-default oracle-java9-unlimited-jce-policy;
  sudo update-java-alternatives -s java-9-oracle; fi
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - BASEURL=https://www-eu.apache.org/dist/maven/maven-3/VERSION/binaries/apache-maven-VERSION-bin.zip
  - FILE=apache-maven-VERSION-bin.zip
  - DIR=apache-maven-VERSION
  - VERSION=3.3.9
  - secure: j6a61/qnfFcSjx5XxmxO2hqBOwtVx5HWrD1+4Atl7WG/pRKz9+jSga1Y7oDAFb2SIl8S65kDmPQB/vC8aHxUDj/Wizjxnxn1FhPqoe9yO6Ztft+984FKFyvj7s6tsBJKcehGec+chTOwZQpH4oI4rU6IlepDHnGLHiOd0Iviryg=
  - secure: GiFr+v2lTQk/sTQB7CYjju1/mupS8LSJupmizLqY454utiZkabDMBOZQnF9ukpy7WhveB9hKQyEKf9iP2w7HSYEjgvogT26vZ5f2MeLnR4SWvqEtf/WBvvh+W+k/rb2f6YgitkB4Jlxn2izemBEDuKplGJphzGW41lf8XZ2IxVI=
install: true
jdk:
- oraclejdk8
language: java
matrix:
  fast_finish: true
  include:
  - jdk: oraclejdk8
  - dist: trusty
    env: JVM=latest
    group: edge
    jdk: oraclejdk9
    sudo: required
script:
- touch NOW
- echo GIBSTUDYSTART $(date)
- mvn clean test verify checkstyle:check findbugs:check -B
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- if [ "$TRAVIS_OS_NAME" == "osx" ];        then echo TESTNUM $(find . -name TEST-*.xml
  -newer NOW | wc -l);        else echo TESTNUM $(find -name TEST-*.xml -newer NOW
  | wc -l);        fi
sudo: false
